schema_version = "1.0.0"
id = "Physical_Motion_Blur"
version = "1.1.0"
name = "Physical Motion Blur"
tagline = "Adds intuitive shutter speed and angle controls for motion blur"
maintainer = "Naoki Korematsu" 
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Camera", "Render", "Animation"]